# Generated by Django 4.1.2 on 2022-10-21 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='films',
            name='director',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='films',
            name='opening_crawl',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='films',
            name='producer',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='films',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='films',
            name='url',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='people',
            name='birth_year',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='people',
            name='homeworld',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='people',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='people',
            name='url',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='planets',
            name='climate',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='planets',
            name='diameter',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='planets',
            name='gravity',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='planets',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='planets',
            name='orbital_period',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='planets',
            name='population',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='planets',
            name='rotation_period',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='planets',
            name='terrain',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='planets',
            name='url',
            field=models.TextField(),
        ),
    ]
